image:
  repository: 078591672268.dkr.ecr.us-east-1.amazonaws.com/platform/tns-app
  digest: sha256:83f96b9c7939321a327baf4166b2cd96d134c28861cf426631abeb3ca5dfae2b

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
