image:
  repository: 078591672268.dkr.ecr.us-east-1.amazonaws.com/platform/tns-db
  digest: sha256:0d60fc4f86e903cf0f4241a8b696feb8b0c2a2f3ab20ae2e9531111cc1f0db68

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
