apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tns-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/platform-workload
    targetRevision: main
    path: base/tns-db
    helm:
      valueFiles:
        - ../../../apps/dev/tns-db/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
